name: GhostBuild

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore GhostExecutor.sln

    - name: Build
      run: msbuild GhostExecutor.sln /p:Configuration=Release /p:Platform="x64"

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Ghost-Final-Build
        path: |
          **/x64/Release/GhostDLL.dll
          **/bin/x64/Release/net6.0-windows/GhostExecutor.exe
