name: Build Ghost Executor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore GhostExecutor.sln

    - name: Build Ghost Project (x64)
      run: msbuild GhostExecutor.sln /p:Configuration=Release /p:Platform="x64"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Ghost-Executor-Build
        path: |
          x64/Release/
          GhostExecutor/bin/x64/Release/
